spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/shopgrid_auth}
    username: ${AUTH_DB_USERNAME:shopgrid}
    password: ${AUTH_DB_PASSWORD:shopgrid}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}

security:
  jwt:
    secret: ${JWT_SECRET:shopgrid-development-secret-key-change-before-production-please-keep-it-long}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:PT1H}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:P14D}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://localhost:4318/v1/traces}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

