spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "com.shopgrid.*"
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/shopgrid_notification}
    username: ${NOTIFICATION_DB_USERNAME:shopgrid}
    password: ${NOTIFICATION_DB_PASSWORD:shopgrid}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8084