apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: shopgrid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: shopgrid
data:
  01-create-databases.sql: |
    CREATE DATABASE shopgrid_auth;
    CREATE DATABASE shopgrid_user;
    CREATE DATABASE shopgrid_product;
    CREATE DATABASE shopgrid_order;
    CREATE DATABASE shopgrid_payment;
    CREATE DATABASE shopgrid_inventory;
    CREATE DATABASE shopgrid_notification;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: shopgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: shopgrid
            - name: POSTGRES_PASSWORD
              value: shopgrid
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-sql
          configMap:
            name: postgres-init