apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: shopgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: cart-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8095
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8083