apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: shopgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: docker.io/library/docker-compose-search-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch:9200
            - name: JAEGER_ENDPOINT
              value: http://jaeger:4318/v1/traces



