spring:
  application:
    name: admin-service
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 9001

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

order-service:
  url: ${ORDER_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://localhost:4318/v1/traces}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

