spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "com.shopgrid.*"
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/shopgrid_order}
    username: ${ORDER_DB_USERNAME:shopgrid}
    password: ${ORDER_DB_PASSWORD:shopgrid}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
resilience4j:
  timelimiter:
    instances:
      productService:
        timeout-duration: 2s
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      productService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      userService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
server:
  port: 8084

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://localhost:4318/v1/traces}

