spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8095

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics